# Get all relics
GET http://localhost:3001/relics/all/David

###
# Get one relic
GET http://localhost:3001/relics/neoN11

###
# Create one relic
POST http://localhost:3001/relics/create
Content-Type: application/json

{
  "name": "Meso D3",
  "id": "mesoD3",
  "drops": [
    "Destreza Prime Blade",
    "Nami Skyla Prime Handle",
    "Kronen Prime Handle",
    "Fang Prime Handle",
    "Braton Prime Stock",
    "Akbolto Prime Blueprint"
  ]
}

###
# Delete one relic
DELETE http://localhost:3001/relics/delete/mesoD3


###

GET https://api.warframe.market/v1/items/ash_prime_set/orders



# USERS

###
# Get userData
GET http://localhost:3001/users/David


###
# Get one relic inventory
GET http://localhost:3001/users/David/mesoD3


###
# Update existing inventory with session drops
PATCH http://localhost:3001/users/David/update/neoK3
Content-Type: application/json

{
  "sessionDrops": [-0, -0, -0, -0, -0, -0],
  "bestStreak": 0
}


###
# Create new empty relic data
PATCH http://localhost:3001/users/David/createrelic
Content-Type: application/json

{
  "id": "mesoD3"
}